/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeFeaturesBefore: typeof import('./src/components/HomeFeaturesBefore/index.vue')['default']
    HomeHeroImage: typeof import('./src/components/HomeHeroImage/index.vue')['default']
    ViaCrowd: typeof import('./src/components/ViaCrowd/index.vue')['default']
    ViaLottiePlayer: typeof import('./src/components/ViaLottiePlayer/index.vue')['default']
    WalineComment: typeof import('./src/components/WalineComment/index.vue')['default']
  }
}
